import { Note } from '../features/notes/utils/NoteTypes.ts';
import { Task } from '../features/tasks/TaskTypes.tsx';

export default Object.freeze({
  taskNotificationBody: `Don't forget to complete your task!`,
});

export const testNotes: Note[] = [
  {
    id: 'test-note-1',
    title: 'Shopping List',
    content: '<html><p>Milk, eggs, bread, and butter</p></html>',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
    isPinned: true,
    reminder: {
      id: 'reminder-1',
      noteId: 'test-note-1',
      time: Date.now() + 3600000,
    },
  },
  {
    id: 'test-note-2',
    title: 'Meeting Notes',
    content: '<html><p>Discuss Q4 goals and budget allocation</p></html>',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 3,
    isPinned: true,
  },
  {
    id: 'test-note-3',
    title: 'Project Ideas',
    content: '<html><ul><li>Mobile app for fitness tracking</li><li>Recipe finder with AI</li></ul></html>',
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 8,
    isPinned: false,
  },
  {
    id: 'test-note-4',
    title: 'Book Recommendations',
    content: '<html><p>Atomic Habits, Deep Work, Thinking Fast and Slow</p></html>',
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now() - 86400000 * 12,
    isPinned: false,
    reminder: {
      id: 'reminder-4',
      noteId: 'test-note-4',
      time: Date.now() + 7200000,
    },
  },
  {
    id: 'test-note-5',
    title: 'Travel Plans',
    content: '<html><p>Visit Tokyo in spring, book flights by March</p></html>',
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now() - 86400000 * 18,
    isPinned: false,
  },
  {
    id: 'test-note-6',
    title: 'Workout Routine',
    content: '<html><p>Monday: Chest, Tuesday: Back, Wednesday: Legs</p></html>',
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
    isPinned: false,
  },
  {
    id: 'test-note-7',
    title: 'Gift Ideas',
    content: '<html><ul><li>Mom: Spa voucher</li><li>Dad: Grilling tools</li></ul></html>',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 6,
    isPinned: false,
    reminder: {
      id: 'reminder-7',
      noteId: 'test-note-7',
      time: Date.now() + 86400000,
    },
  },
  {
    id: 'test-note-8',
    title: 'Password Hints',
    content: '<html><p>Bank: favorite pet + birth year</p></html>',
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000 * 25,
    isPinned: true,
  },
  {
    id: 'test-note-9',
    title: 'Recipe: Pasta Carbonara',
    content: '<html><p>Eggs, pecorino, guanciale, black pepper</p></html>',
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 2,
    isPinned: false,
  },
  {
    id: 'test-note-10',
    title: 'Job Applications',
    content: '<html><ul><li>TechCorp - applied</li><li>StartupXYZ - pending</li></ul></html>',
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now() - 86400000 * 10,
    isPinned: false,
    reminder: {
      id: 'reminder-10',
      noteId: 'test-note-10',
      time: Date.now() + 172800000,
    },
  },
  {
    id: 'test-note-11',
    title: 'Birthday Party Planning',
    content: '<html><p>Book venue, send invites, order cake</p></html>',
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 5,
    isPinned: true,
  },
  {
    id: 'test-note-12',
    title: 'Car Maintenance',
    content: '<html><p>Oil change due at 50,000 miles</p></html>',
    createdAt: Date.now() - 86400000 * 45,
    updatedAt: Date.now() - 86400000 * 40,
    isPinned: false,
  },
  {
    id: 'test-note-13',
    title: 'Learning Goals',
    content: '<html><ul><li>TypeScript advanced patterns</li><li>React Native animations</li></ul></html>',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 1,
    isPinned: false,
    reminder: {
      id: 'reminder-13',
      noteId: 'test-note-13',
      time: Date.now() + 43200000,
    },
  },
  {
    id: 'test-note-14',
    title: 'Dentist Appointment',
    content: '<html><p>Dr. Smith - 123 Main St - (555) 123-4567</p></html>',
    createdAt: Date.now() - 86400000 * 25,
    updatedAt: Date.now() - 86400000 * 20,
    isPinned: false,
  },
  {
    id: 'test-note-15',
    title: 'Home Renovation Ideas',
    content: '<html><p>Paint kitchen blue, new countertops, backsplash</p></html>',
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now() - 86400000 * 10,
    isPinned: false,
  },
  {
    id: 'test-note-16',
    title: 'Savings Goals',
    content: '<html><p>Emergency fund: $10,000 - Currently: $6,500</p></html>',
    createdAt: Date.now() - 86400000 * 60,
    updatedAt: Date.now() - 86400000 * 50,
    isPinned: true,
    reminder: {
      id: 'reminder-16',
      noteId: 'test-note-16',
      time: Date.now() + 259200000,
    },
  },
  {
    id: 'test-note-17',
    title: 'Podcast Episodes',
    content: '<html><ul><li>Episode 42 - AI trends</li><li>Episode 43 - Remote work</li></ul></html>',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 4,
    isPinned: false,
  },
  {
    id: 'test-note-18',
    title: 'WiFi Passwords',
    content: '<html><p>Home: MySecureWifi2024</p><p>Guest: WelcomeGuest</p></html>',
    createdAt: Date.now() - 86400000 * 90,
    updatedAt: Date.now() - 86400000 * 80,
    isPinned: true,
  },
  {
    id: 'test-note-19',
    title: 'Movie Watchlist',
    content: '<html><p>Oppenheimer, Dune Part 2, Poor Things</p></html>',
    createdAt: Date.now() - 86400000 * 9,
    updatedAt: Date.now() - 86400000 * 7,
    isPinned: false,
  },
  {
    id: 'test-note-20',
    title: 'Conference Talk Ideas',
    content: '<html><p>React Native performance optimization tips</p></html>',
    createdAt: Date.now() - 86400000 * 11,
    updatedAt: Date.now() - 86400000 * 9,
    isPinned: false,
    reminder: {
      id: 'reminder-20',
      noteId: 'test-note-20',
      time: Date.now() + 604800000,
    },
  },
  {
    id: 'test-note-21',
    title: 'Plant Care Schedule',
    content: '<html><p>Monstera: water weekly, Fiddle Leaf: mist daily</p></html>',
    createdAt: Date.now() - 86400000 * 13,
    updatedAt: Date.now() - 86400000 * 11,
    isPinned: false,
  },
  {
    id: 'test-note-22',
    title: 'Tax Documents Checklist',
    content: '<html><ul><li>W-2 forms</li><li>Investment statements</li><li>Charitable donations</li></ul></html>',
    createdAt: Date.now() - 86400000 * 35,
    updatedAt: Date.now() - 86400000 * 30,
    isPinned: true,
  },
  {
    id: 'test-note-23',
    title: 'Restaurant Reviews',
    content: '<html><p>Italian Place: 5/5, Sushi Bar: 4/5</p></html>',
    createdAt: Date.now() - 86400000 * 18,
    updatedAt: Date.now() - 86400000 * 15,
    isPinned: false,
    reminder: {
      id: 'reminder-23',
      noteId: 'test-note-23',
      time: Date.now() + 10800000,
    },
  },
  {
    id: 'test-note-24',
    title: 'Code Snippets',
    content: '<html><p>useEffect cleanup pattern, custom hooks</p></html>',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000,
    isPinned: false,
  },
  {
    id: 'test-note-25',
    title: 'Yearly Goals Review',
    content: '<html><p>Q1: Learn TypeScript ✓, Q2: Build side project</p></html>',
    createdAt: Date.now() - 86400000 * 100,
    updatedAt: Date.now() - 86400000 * 50,
    isPinned: true,
  },
];

export const testTasks: Task[] = [
  {
    id: 'test-task-1',
    title: 'Buy groceries',
    completed: false,
    reminder: {
      id: 'task-reminder-1',
      taskId: 'test-task-1',
      time: Date.now() + 3600000,
    },
    subTasks: [
      { title: 'Get milk', completed: true },
      { title: 'Get eggs', completed: false },
    ],
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: 'test-task-2',
    title: 'Finish project report',
    completed: false,
    subTasks: [
      { title: 'Write introduction', completed: true },
      { title: 'Add charts', completed: true },
      { title: 'Proofread', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'test-task-3',
    title: 'Call dentist',
    completed: true,
    subTasks: [],
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'test-task-4',
    title: 'Schedule car service',
    completed: false,
    reminder: {
      id: 'task-reminder-4',
      taskId: 'test-task-4',
      time: Date.now() + 86400000,
    },
    subTasks: [
      { title: 'Find mechanic', completed: false },
      { title: 'Book appointment', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: 'test-task-5',
    title: 'Pay utility bills',
    completed: false,
    subTasks: [
      { title: 'Electric', completed: true },
      { title: 'Water', completed: false },
      { title: 'Internet', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 6,
  },
  {
    id: 'test-task-6',
    title: 'Clean garage',
    completed: false,
    reminder: {
      id: 'task-reminder-6',
      taskId: 'test-task-6',
      time: Date.now() + 172800000,
    },
    subTasks: [
      { title: 'Sort tools', completed: false },
      { title: 'Donate old items', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 8,
  },
  {
    id: 'test-task-7',
    title: 'Update resume',
    completed: true,
    subTasks: [
      { title: 'Add recent experience', completed: true },
      { title: 'Update skills section', completed: true },
    ],
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now() - 86400000 * 12,
  },
  {
    id: 'test-task-8',
    title: 'Plan weekend trip',
    completed: false,
    subTasks: [
      { title: 'Book hotel', completed: true },
      { title: 'Research activities', completed: false },
      { title: 'Pack bags', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'test-task-9',
    title: 'Fix leaky faucet',
    completed: false,
    reminder: {
      id: 'task-reminder-9',
      taskId: 'test-task-9',
      time: Date.now() + 7200000,
    },
    subTasks: [],
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: 'test-task-10',
    title: 'Submit expense report',
    completed: true,
    subTasks: [
      { title: 'Gather receipts', completed: true },
      { title: 'Fill out form', completed: true },
      { title: 'Submit to accounting', completed: true },
    ],
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 7,
  },
  {
    id: 'test-task-11',
    title: 'Organize photos',
    completed: false,
    subTasks: [
      { title: 'Delete duplicates', completed: false },
      { title: 'Create albums', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now() - 86400000 * 18,
  },
  {
    id: 'test-task-12',
    title: 'Renew gym membership',
    completed: false,
    reminder: {
      id: 'task-reminder-12',
      taskId: 'test-task-12',
      time: Date.now() + 259200000,
    },
    subTasks: [],
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now() - 86400000 * 14,
  },
  {
    id: 'test-task-13',
    title: 'Read book chapter',
    completed: true,
    subTasks: [
      { title: 'Chapter 5', completed: true },
      { title: 'Take notes', completed: true },
    ],
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: 'test-task-14',
    title: 'Backup computer',
    completed: false,
    subTasks: [
      { title: 'External drive', completed: false },
      { title: 'Cloud backup', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now() - 86400000 * 10,
  },
  {
    id: 'test-task-15',
    title: 'Buy birthday gift',
    completed: false,
    reminder: {
      id: 'task-reminder-15',
      taskId: 'test-task-15',
      time: Date.now() + 432000000,
    },
    subTasks: [
      { title: 'Research ideas', completed: true },
      { title: 'Purchase gift', completed: false },
      { title: 'Wrap gift', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 9,
    updatedAt: Date.now() - 86400000 * 7,
  },
  {
    id: 'test-task-16',
    title: 'Meal prep for week',
    completed: true,
    subTasks: [
      { title: 'Plan meals', completed: true },
      { title: 'Go shopping', completed: true },
      { title: 'Cook meals', completed: true },
    ],
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now(),
  },
  {
    id: 'test-task-17',
    title: 'Fix broken shelf',
    completed: false,
    subTasks: [
      { title: 'Buy brackets', completed: false },
      { title: 'Get screws', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 11,
    updatedAt: Date.now() - 86400000 * 9,
  },
  {
    id: 'test-task-18',
    title: 'Review insurance policy',
    completed: false,
    reminder: {
      id: 'task-reminder-18',
      taskId: 'test-task-18',
      time: Date.now() + 604800000,
    },
    subTasks: [],
    createdAt: Date.now() - 86400000 * 25,
    updatedAt: Date.now() - 86400000 * 20,
  },
  {
    id: 'test-task-19',
    title: 'Wash car',
    completed: true,
    subTasks: [
      { title: 'Exterior wash', completed: true },
      { title: 'Interior vacuum', completed: true },
      { title: 'Wax', completed: true },
    ],
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'test-task-20',
    title: 'Learn new recipe',
    completed: false,
    subTasks: [
      { title: 'Watch tutorial', completed: true },
      { title: 'Buy ingredients', completed: false },
      { title: 'Practice cooking', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'test-task-21',
    title: 'Schedule doctor checkup',
    completed: false,
    reminder: {
      id: 'task-reminder-21',
      taskId: 'test-task-21',
      time: Date.now() + 1296000000,
    },
    subTasks: [
      { title: 'Find doctor', completed: false },
      { title: 'Call for appointment', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 16,
    updatedAt: Date.now() - 86400000 * 14,
  },
  {
    id: 'test-task-22',
    title: 'Organize closet',
    completed: false,
    subTasks: [
      { title: 'Sort clothes', completed: false },
      { title: 'Donate unused items', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 22,
    updatedAt: Date.now() - 86400000 * 20,
  },
  {
    id: 'test-task-23',
    title: 'Set up budget tracker',
    completed: true,
    subTasks: [
      { title: 'Research apps', completed: true },
      { title: 'Download app', completed: true },
      { title: 'Input data', completed: true },
    ],
    createdAt: Date.now() - 86400000 * 18,
    updatedAt: Date.now() - 86400000 * 15,
  },
  {
    id: 'test-task-24',
    title: 'Plant herbs',
    completed: false,
    subTasks: [
      { title: 'Buy seeds', completed: true },
      { title: 'Prepare pots', completed: false },
      { title: 'Plant seeds', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 6,
  },
  {
    id: 'test-task-25',
    title: 'Research new laptop',
    completed: false,
    reminder: {
      id: 'task-reminder-25',
      taskId: 'test-task-25',
      time: Date.now() + 21600000,
    },
    subTasks: [
      { title: 'Compare models', completed: false },
      { title: 'Read reviews', completed: false },
      { title: 'Check prices', completed: false },
    ],
    createdAt: Date.now() - 86400000 * 13,
    updatedAt: Date.now() - 86400000 * 11,
  },
];
